name: namaapptaskshohan
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  http: ^0.12.1
  provider: ^4.1.3
  intl: ^0.15.8
  flutter_spinkit: ^4.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - images/
    - images/hmbrger.png
    - images/daarlogo.png
    - images/loan.png
    - images/splash.png
    - images/plac.png
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: dubai
      fonts:
        - asset: fonts/dubai.ttf
          weight: 900
